[build]
  command = "grow install && GROW_THREADS=1 grow build && cp robots-demo.txt build/robots.txt"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.8"

[context.deploy-preview]
  command = "grow install && GROW_THREADS=1 grow build && cp robots-demo.txt build/robots.txt"